# Change baseurl before deploy
baseurl      = "https://lulubrand.github.io/"
languageCode = "zh-cn"
title        = "LuluBd 的博客"

# Theme i18n support
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = true

[pagination]
    pagerSize = 5
